# Generated by Django 3.2.14 on 2022-10-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('phoneno', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=250)),
                ('debitnotebook', models.TextField(default=True)),
                ('pen', models.TextField(default=True)),
                ('exampaper', models.TextField(default=True)),
            ],
        ),
    ]
